# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 00:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import test_task.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='random_int',
            field=models.IntegerField(default=test_task.models.get_random_integer, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
